# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_api import ServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v11_service_active_get(self):
        """Test case for api_v11_service_active_get

        Gets all services within PTV as a list of service ids and names. Also services with draft and modified versions are included.  Services created/modified after certain date can be fetched by adding date as query string parameter.  Services created/modified before certain date can be fetched by adding dateBefore as query string parameter.  NOTE! This is a restricted endpoint.  # noqa: E501
        """
        pass

    def test_api_v11_service_active_id_get(self):
        """Test case for api_v11_service_active_id_get

        Fetches all the information related to a single service. Also services with only draft or modified versions are returned.  NOTE! This is a restricted endpoint.  # noqa: E501
        """
        pass

    def test_api_v11_service_archived_list_get(self):
        """Test case for api_v11_service_archived_list_get

        Fetches automatically/manually archived services  # noqa: E501
        """
        pass

    def test_api_v11_service_area_area_code_code_get(self):
        """Test case for api_v11_service_area_area_code_code_get

        Gets a list of published services related to defined area and code.  Services created/modified after certain date can be fetched by adding date as query string parameter.  Services created/modified before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass

    def test_api_v11_service_get(self):
        """Test case for api_v11_service_get

        Gets all the published services within PTV as a list of service ids and names.  Services created/modified after certain date can be fetched by adding date as query string parameter.  Services created/modified before certain date can be fetched by adding dateBefore as query string parameter.  Archived items can be fetched by setting status parameter as 'Archived' and withdrawn items can be fetched by setting status parameter as 'Withdrawn'.  # noqa: E501
        """
        pass

    def test_api_v11_service_id_get(self):
        """Test case for api_v11_service_id_get

        Fetches all the information related to a single service.  # noqa: E501
        """
        pass

    def test_api_v11_service_id_put(self):
        """Test case for api_v11_service_id_put

        Updates the defined service with the data provided as input.  # noqa: E501
        """
        pass

    def test_api_v11_service_industrial_class_get(self):
        """Test case for api_v11_service_industrial_class_get

        Gets a list of published services for defined industrial class.  Services created/modified after certain date can be fetched by adding date as query string parameter.  Services created/modified before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass

    def test_api_v11_service_list_area_area_code_code_get(self):
        """Test case for api_v11_service_list_area_area_code_code_get

        Fetches all the information of published services related to certain area and code.  User can set serviceWithGD parameter to true to include possible attached general description data into the service data.  In this case general description related descriptions are marked with prefix 'GD_' to separate them from service related descriptions.  # noqa: E501
        """
        pass

    def test_api_v11_service_list_get(self):
        """Test case for api_v11_service_list_get

        Fetches all the information related to requested services.  # noqa: E501
        """
        pass

    def test_api_v11_service_list_organization_get(self):
        """Test case for api_v11_service_list_organization_get

        Fetches all the information of the services related to certain organization. Either organizationId, code or oid needs to be added as a parameter.  User can also set serviceWithGD parameter to true to include possible attached general description data into the service data.  In this case general description related descriptions are marked with prefix 'GD_' to separate them from service related descriptions.  # noqa: E501
        """
        pass

    def test_api_v11_service_post(self):
        """Test case for api_v11_service_post

        Creates a new service with the data provided as input.  # noqa: E501
        """
        pass

    def test_api_v11_service_service_channel_service_channel_id_get(self):
        """Test case for api_v11_service_service_channel_service_channel_id_get

        Gets a list of published services for defined service channel.  Services joined to service channel after certain date can be fetched by adding date as query string parameter.  Services joined to service channel before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass

    def test_api_v11_service_service_class_get(self):
        """Test case for api_v11_service_service_class_get

        Gets a list of published services for defined service class.  Services created/modified after certain date can be fetched by adding date as query string parameter.  Services created/modified before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass

    def test_api_v11_service_service_with_gd_id_get(self):
        """Test case for api_v11_service_service_with_gd_id_get

        Fetches all the information related to a single service. If general description is attached also general description data is returned within the service data.  General description related descriptions are marked with prefix 'GD_' to separate them from service related descriptions.  # noqa: E501
        """
        pass

    def test_api_v11_service_service_with_gd_list_get(self):
        """Test case for api_v11_service_service_with_gd_list_get

        Fetches all the information related to requests services. If general description is attached to a service also general description data is returned within the service data.  General description related descriptions are marked with prefix 'GD_' to separate them from service related descriptions.  # noqa: E501
        """
        pass

    def test_api_v11_service_source_id_source_id_put(self):
        """Test case for api_v11_service_source_id_source_id_put

        Updates the defined service with the data provided as input.  # noqa: E501
        """
        pass

    def test_api_v11_service_target_group_get(self):
        """Test case for api_v11_service_target_group_get

        Gets a list of published services for defined target group.  Services created/modified after certain date can be fetched by adding date as query string parameter.  Services created/modified before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass

    def test_api_v11_service_type_type_get(self):
        """Test case for api_v11_service_type_type_get

        Gets a list of published services of defined service type.  Services created/modified after certain date can be fetched by adding date as query string parameter.  Services created/modified before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
