# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.common_api import CommonApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommonApi(unittest.TestCase):
    """CommonApi unit test stubs"""

    def setUp(self):
        self.api = CommonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v11_common_channels_without_services_get(self):
        """Test case for api_v11_common_channels_without_services_get

        Gets information of user's organization's channels that have no connections to services.  # noqa: E501
        """
        pass

    def test_api_v11_common_entities_by_organization_organization_id_get(self):
        """Test case for api_v11_common_entities_by_organization_organization_id_get

        Gets a list of published services and service channels by organization.  Services/channels created/modified after certain date can be fetched by adding date as query string parameter.  Services/channels created/modified before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass

    def test_api_v11_common_expiring_service_channels_get(self):
        """Test case for api_v11_common_expiring_service_channels_get

        Gets information of user's organization's expiring service channels.  # noqa: E501
        """
        pass

    def test_api_v11_common_not_maintained_service_channels_get(self):
        """Test case for api_v11_common_not_maintained_service_channels_get

        Gets information of user's organization's not updated channels.  # noqa: E501
        """
        pass

    def test_api_v11_common_not_maintained_services_get(self):
        """Test case for api_v11_common_not_maintained_services_get

        Gets information of user's organization's not updated services.  # noqa: E501
        """
        pass

    def test_api_v11_common_services_without_channels_get(self):
        """Test case for api_v11_common_services_without_channels_get

        Gets information of user's organization's services that have no connections to channels.  # noqa: E501
        """
        pass

    def test_api_v11_common_translation_get(self):
        """Test case for api_v11_common_translation_get

        Gets information of translation processes within PTV.  Translation items created/modified after certain date can be fetched by adding date as query string parameter.  Translation items created/modified before certain date can be fetched by adding dateBefore as query string parameter.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
