# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vm_open_api_address_post_office_box import VmOpenApiAddressPostOfficeBox  # noqa: E501
from swagger_client.rest import ApiException


class TestVmOpenApiAddressPostOfficeBox(unittest.TestCase):
    """VmOpenApiAddressPostOfficeBox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVmOpenApiAddressPostOfficeBox(self):
        """Test VmOpenApiAddressPostOfficeBox"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vm_open_api_address_post_office_box.VmOpenApiAddressPostOfficeBox()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
