# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v9_vm_open_api_service_in import V9VmOpenApiServiceIn  # noqa: E501
from swagger_client.rest import ApiException


class TestV9VmOpenApiServiceIn(unittest.TestCase):
    """V9VmOpenApiServiceIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV9VmOpenApiServiceIn(self):
        """Test V9VmOpenApiServiceIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v9_vm_open_api_service_in.V9VmOpenApiServiceIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
