# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v11_vm_open_api_phone_channel_in import V11VmOpenApiPhoneChannelIn  # noqa: E501
from swagger_client.rest import ApiException


class TestV11VmOpenApiPhoneChannelIn(unittest.TestCase):
    """V11VmOpenApiPhoneChannelIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV11VmOpenApiPhoneChannelIn(self):
        """Test V11VmOpenApiPhoneChannelIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v11_vm_open_api_phone_channel_in.V11VmOpenApiPhoneChannelIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
