# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vm_open_api_not_updated_task import VmOpenApiNotUpdatedTask  # noqa: E501
from swagger_client.rest import ApiException


class TestVmOpenApiNotUpdatedTask(unittest.TestCase):
    """VmOpenApiNotUpdatedTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVmOpenApiNotUpdatedTask(self):
        """Test VmOpenApiNotUpdatedTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vm_open_api_not_updated_task.VmOpenApiNotUpdatedTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
