# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vm_open_api_accessibility_classification import VmOpenApiAccessibilityClassification  # noqa: E501
from swagger_client.rest import ApiException


class TestVmOpenApiAccessibilityClassification(unittest.TestCase):
    """VmOpenApiAccessibilityClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVmOpenApiAccessibilityClassification(self):
        """Test VmOpenApiAccessibilityClassification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vm_open_api_accessibility_classification.VmOpenApiAccessibilityClassification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
