# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ISecurityOwnOrganization(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_own_organization': 'bool',
        'id': 'str'
    }

    attribute_map = {
        'is_own_organization': 'isOwnOrganization',
        'id': 'id'
    }

    def __init__(self, is_own_organization=None, id=None):  # noqa: E501
        """ISecurityOwnOrganization - a model defined in Swagger"""  # noqa: E501
        self._is_own_organization = None
        self._id = None
        self.discriminator = None
        if is_own_organization is not None:
            self.is_own_organization = is_own_organization
        if id is not None:
            self.id = id

    @property
    def is_own_organization(self):
        """Gets the is_own_organization of this ISecurityOwnOrganization.  # noqa: E501

        Entity belongs to user organization structure  # noqa: E501

        :return: The is_own_organization of this ISecurityOwnOrganization.  # noqa: E501
        :rtype: bool
        """
        return self._is_own_organization

    @is_own_organization.setter
    def is_own_organization(self, is_own_organization):
        """Sets the is_own_organization of this ISecurityOwnOrganization.

        Entity belongs to user organization structure  # noqa: E501

        :param is_own_organization: The is_own_organization of this ISecurityOwnOrganization.  # noqa: E501
        :type: bool
        """

        self._is_own_organization = is_own_organization

    @property
    def id(self):
        """Gets the id of this ISecurityOwnOrganization.  # noqa: E501

        Entity identifier.  # noqa: E501

        :return: The id of this ISecurityOwnOrganization.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ISecurityOwnOrganization.

        Entity identifier.  # noqa: E501

        :param id: The id of this ISecurityOwnOrganization.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ISecurityOwnOrganization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ISecurityOwnOrganization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
