# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V11VmOpenApiElectronicChannelInBase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_id': 'str',
        'support_emails': 'list[VmOpenApiLanguageItem]',
        'languages': 'list[str]',
        'is_visible_for_all': 'bool',
        'channel_id': 'str',
        'version_id': 'str',
        'id': 'str',
        'organization_id': 'str',
        'service_channel_names_with_type': 'list[VmOpenApiLocalizedListItem]',
        'delete_all_service_hours': 'bool',
        'delete_all_support_emails': 'bool',
        'delete_all_support_phones': 'bool',
        'valid_from': 'datetime',
        'valid_to': 'datetime',
        'current_publishing_status': 'str',
        'service_channel_services': 'list[str]',
        'user_name': 'str',
        'service_channel_names': 'list[VmOpenApiLanguageItem]',
        'signature_quantity': 'str',
        'requires_signature': 'bool',
        'requires_authentication': 'bool',
        'web_page': 'list[VmOpenApiLanguageItem]',
        'attachments': 'list[VmOpenApiAttachment]',
        'accessibility_classification': 'list[VmOpenApiAccessibilityClassification]',
        'delete_all_attachments': 'bool',
        'web_pages': 'list[V9VmOpenApiWebPage]',
        'delete_all_web_pages': 'bool',
        'available_languages': 'list[str]',
        'required_properties_available_languages': 'list[str]',
        'service_channel_descriptions': 'list[VmOpenApiLocalizedListItem]',
        'area_type': 'str',
        'areas': 'list[VmOpenApiAreaIn]',
        'support_phones': 'list[V4VmOpenApiPhone]',
        'service_hours': 'list[V11VmOpenApiServiceHour]',
        'publishing_status': 'str'
    }

    attribute_map = {
        'source_id': 'sourceId',
        'support_emails': 'supportEmails',
        'languages': 'languages',
        'is_visible_for_all': 'isVisibleForAll',
        'channel_id': 'channelId',
        'version_id': 'versionId',
        'id': 'id',
        'organization_id': 'organizationId',
        'service_channel_names_with_type': 'serviceChannelNamesWithType',
        'delete_all_service_hours': 'deleteAllServiceHours',
        'delete_all_support_emails': 'deleteAllSupportEmails',
        'delete_all_support_phones': 'deleteAllSupportPhones',
        'valid_from': 'validFrom',
        'valid_to': 'validTo',
        'current_publishing_status': 'currentPublishingStatus',
        'service_channel_services': 'serviceChannelServices',
        'user_name': 'userName',
        'service_channel_names': 'serviceChannelNames',
        'signature_quantity': 'signatureQuantity',
        'requires_signature': 'requiresSignature',
        'requires_authentication': 'requiresAuthentication',
        'web_page': 'webPage',
        'attachments': 'attachments',
        'accessibility_classification': 'accessibilityClassification',
        'delete_all_attachments': 'deleteAllAttachments',
        'web_pages': 'webPages',
        'delete_all_web_pages': 'deleteAllWebPages',
        'available_languages': 'availableLanguages',
        'required_properties_available_languages': 'requiredPropertiesAvailableLanguages',
        'service_channel_descriptions': 'serviceChannelDescriptions',
        'area_type': 'areaType',
        'areas': 'areas',
        'support_phones': 'supportPhones',
        'service_hours': 'serviceHours',
        'publishing_status': 'publishingStatus'
    }

    def __init__(self, source_id=None, support_emails=None, languages=None, is_visible_for_all=None, channel_id=None, version_id=None, id=None, organization_id=None, service_channel_names_with_type=None, delete_all_service_hours=None, delete_all_support_emails=None, delete_all_support_phones=None, valid_from=None, valid_to=None, current_publishing_status=None, service_channel_services=None, user_name=None, service_channel_names=None, signature_quantity=None, requires_signature=None, requires_authentication=None, web_page=None, attachments=None, accessibility_classification=None, delete_all_attachments=None, web_pages=None, delete_all_web_pages=None, available_languages=None, required_properties_available_languages=None, service_channel_descriptions=None, area_type=None, areas=None, support_phones=None, service_hours=None, publishing_status=None):  # noqa: E501
        """V11VmOpenApiElectronicChannelInBase - a model defined in Swagger"""  # noqa: E501
        self._source_id = None
        self._support_emails = None
        self._languages = None
        self._is_visible_for_all = None
        self._channel_id = None
        self._version_id = None
        self._id = None
        self._organization_id = None
        self._service_channel_names_with_type = None
        self._delete_all_service_hours = None
        self._delete_all_support_emails = None
        self._delete_all_support_phones = None
        self._valid_from = None
        self._valid_to = None
        self._current_publishing_status = None
        self._service_channel_services = None
        self._user_name = None
        self._service_channel_names = None
        self._signature_quantity = None
        self._requires_signature = None
        self._requires_authentication = None
        self._web_page = None
        self._attachments = None
        self._accessibility_classification = None
        self._delete_all_attachments = None
        self._web_pages = None
        self._delete_all_web_pages = None
        self._available_languages = None
        self._required_properties_available_languages = None
        self._service_channel_descriptions = None
        self._area_type = None
        self._areas = None
        self._support_phones = None
        self._service_hours = None
        self._publishing_status = None
        self.discriminator = None
        if source_id is not None:
            self.source_id = source_id
        if support_emails is not None:
            self.support_emails = support_emails
        if languages is not None:
            self.languages = languages
        if is_visible_for_all is not None:
            self.is_visible_for_all = is_visible_for_all
        if channel_id is not None:
            self.channel_id = channel_id
        if version_id is not None:
            self.version_id = version_id
        if id is not None:
            self.id = id
        if organization_id is not None:
            self.organization_id = organization_id
        if service_channel_names_with_type is not None:
            self.service_channel_names_with_type = service_channel_names_with_type
        if delete_all_service_hours is not None:
            self.delete_all_service_hours = delete_all_service_hours
        if delete_all_support_emails is not None:
            self.delete_all_support_emails = delete_all_support_emails
        if delete_all_support_phones is not None:
            self.delete_all_support_phones = delete_all_support_phones
        if valid_from is not None:
            self.valid_from = valid_from
        if valid_to is not None:
            self.valid_to = valid_to
        if current_publishing_status is not None:
            self.current_publishing_status = current_publishing_status
        if service_channel_services is not None:
            self.service_channel_services = service_channel_services
        if user_name is not None:
            self.user_name = user_name
        if service_channel_names is not None:
            self.service_channel_names = service_channel_names
        if signature_quantity is not None:
            self.signature_quantity = signature_quantity
        if requires_signature is not None:
            self.requires_signature = requires_signature
        self.requires_authentication = requires_authentication
        if web_page is not None:
            self.web_page = web_page
        if attachments is not None:
            self.attachments = attachments
        if accessibility_classification is not None:
            self.accessibility_classification = accessibility_classification
        if delete_all_attachments is not None:
            self.delete_all_attachments = delete_all_attachments
        if web_pages is not None:
            self.web_pages = web_pages
        if delete_all_web_pages is not None:
            self.delete_all_web_pages = delete_all_web_pages
        if available_languages is not None:
            self.available_languages = available_languages
        if required_properties_available_languages is not None:
            self.required_properties_available_languages = required_properties_available_languages
        if service_channel_descriptions is not None:
            self.service_channel_descriptions = service_channel_descriptions
        if area_type is not None:
            self.area_type = area_type
        if areas is not None:
            self.areas = areas
        if support_phones is not None:
            self.support_phones = support_phones
        if service_hours is not None:
            self.service_hours = service_hours
        if publishing_status is not None:
            self.publishing_status = publishing_status

    @property
    def source_id(self):
        """Gets the source_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        External system identifier for this service channel. User needs to be logged in to be able to get/set value.  # noqa: E501

        :return: The source_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this V11VmOpenApiElectronicChannelInBase.

        External system identifier for this service channel. User needs to be logged in to be able to get/set value.  # noqa: E501

        :param source_id: The source_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._source_id = source_id

    @property
    def support_emails(self):
        """Gets the support_emails of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of support email addresses for the service channel. (Max.Length: 100).  # noqa: E501

        :return: The support_emails of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiLanguageItem]
        """
        return self._support_emails

    @support_emails.setter
    def support_emails(self, support_emails):
        """Sets the support_emails of this V11VmOpenApiElectronicChannelInBase.

        List of support email addresses for the service channel. (Max.Length: 100).  # noqa: E501

        :param support_emails: The support_emails of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiLanguageItem]
        """

        self._support_emails = support_emails

    @property
    def languages(self):
        """Gets the languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of languages the service channel is available in (two letter language code).  # noqa: E501

        :return: The languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[str]
        """
        return self._languages

    @languages.setter
    def languages(self, languages):
        """Sets the languages of this V11VmOpenApiElectronicChannelInBase.

        List of languages the service channel is available in (two letter language code).  # noqa: E501

        :param languages: The languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[str]
        """

        self._languages = languages

    @property
    def is_visible_for_all(self):
        """Gets the is_visible_for_all of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Indicates if channel can be used (referenced within services) by other users from other organizations.  # noqa: E501

        :return: The is_visible_for_all of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._is_visible_for_all

    @is_visible_for_all.setter
    def is_visible_for_all(self, is_visible_for_all):
        """Sets the is_visible_for_all of this V11VmOpenApiElectronicChannelInBase.

        Indicates if channel can be used (referenced within services) by other users from other organizations.  # noqa: E501

        :param is_visible_for_all: The is_visible_for_all of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """

        self._is_visible_for_all = is_visible_for_all

    @property
    def channel_id(self):
        """Gets the channel_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Gets or sets the special channel identifier.  # noqa: E501

        :return: The channel_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """Sets the channel_id of this V11VmOpenApiElectronicChannelInBase.

        Gets or sets the special channel identifier.  # noqa: E501

        :param channel_id: The channel_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._channel_id = channel_id

    @property
    def version_id(self):
        """Gets the version_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        The identifier for current version.  # noqa: E501

        :return: The version_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._version_id

    @version_id.setter
    def version_id(self, version_id):
        """Sets the version_id of this V11VmOpenApiElectronicChannelInBase.

        The identifier for current version.  # noqa: E501

        :param version_id: The version_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._version_id = version_id

    @property
    def id(self):
        """Gets the id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        PTV identifier for the service channel.  # noqa: E501

        :return: The id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V11VmOpenApiElectronicChannelInBase.

        PTV identifier for the service channel.  # noqa: E501

        :param id: The id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def organization_id(self):
        """Gets the organization_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        PTV organization identifier for organization responsible for this service channel.  # noqa: E501

        :return: The organization_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this V11VmOpenApiElectronicChannelInBase.

        PTV organization identifier for organization responsible for this service channel.  # noqa: E501

        :param organization_id: The organization_id of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def service_channel_names_with_type(self):
        """Gets the service_channel_names_with_type of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Localized list of service channel names.  # noqa: E501

        :return: The service_channel_names_with_type of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiLocalizedListItem]
        """
        return self._service_channel_names_with_type

    @service_channel_names_with_type.setter
    def service_channel_names_with_type(self, service_channel_names_with_type):
        """Sets the service_channel_names_with_type of this V11VmOpenApiElectronicChannelInBase.

        Localized list of service channel names.  # noqa: E501

        :param service_channel_names_with_type: The service_channel_names_with_type of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiLocalizedListItem]
        """

        self._service_channel_names_with_type = service_channel_names_with_type

    @property
    def delete_all_service_hours(self):
        """Gets the delete_all_service_hours of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Set to true to delete all existing service hours for the service channel. The ServiceHours collection should be empty when this property is set to true.  # noqa: E501

        :return: The delete_all_service_hours of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._delete_all_service_hours

    @delete_all_service_hours.setter
    def delete_all_service_hours(self, delete_all_service_hours):
        """Sets the delete_all_service_hours of this V11VmOpenApiElectronicChannelInBase.

        Set to true to delete all existing service hours for the service channel. The ServiceHours collection should be empty when this property is set to true.  # noqa: E501

        :param delete_all_service_hours: The delete_all_service_hours of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """

        self._delete_all_service_hours = delete_all_service_hours

    @property
    def delete_all_support_emails(self):
        """Gets the delete_all_support_emails of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Set to true to delete all existing support email addresses for the service channel. The SupportEmails collection should be empty when this property is set to true.  # noqa: E501

        :return: The delete_all_support_emails of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._delete_all_support_emails

    @delete_all_support_emails.setter
    def delete_all_support_emails(self, delete_all_support_emails):
        """Sets the delete_all_support_emails of this V11VmOpenApiElectronicChannelInBase.

        Set to true to delete all existing support email addresses for the service channel. The SupportEmails collection should be empty when this property is set to true.  # noqa: E501

        :param delete_all_support_emails: The delete_all_support_emails of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """

        self._delete_all_support_emails = delete_all_support_emails

    @property
    def delete_all_support_phones(self):
        """Gets the delete_all_support_phones of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Set to true to delete all existing support phone numbers for the service channel. The SupportPhones collection should be empty when this property is set to true.  # noqa: E501

        :return: The delete_all_support_phones of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._delete_all_support_phones

    @delete_all_support_phones.setter
    def delete_all_support_phones(self, delete_all_support_phones):
        """Sets the delete_all_support_phones of this V11VmOpenApiElectronicChannelInBase.

        Set to true to delete all existing support phone numbers for the service channel. The SupportPhones collection should be empty when this property is set to true.  # noqa: E501

        :param delete_all_support_phones: The delete_all_support_phones of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """

        self._delete_all_support_phones = delete_all_support_phones

    @property
    def valid_from(self):
        """Gets the valid_from of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Date when item should be published.  # noqa: E501

        :return: The valid_from of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: datetime
        """
        return self._valid_from

    @valid_from.setter
    def valid_from(self, valid_from):
        """Sets the valid_from of this V11VmOpenApiElectronicChannelInBase.

        Date when item should be published.  # noqa: E501

        :param valid_from: The valid_from of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: datetime
        """

        self._valid_from = valid_from

    @property
    def valid_to(self):
        """Gets the valid_to of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Date when item should be archived.  # noqa: E501

        :return: The valid_to of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: datetime
        """
        return self._valid_to

    @valid_to.setter
    def valid_to(self, valid_to):
        """Sets the valid_to of this V11VmOpenApiElectronicChannelInBase.

        Date when item should be archived.  # noqa: E501

        :param valid_to: The valid_to of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: datetime
        """

        self._valid_to = valid_to

    @property
    def current_publishing_status(self):
        """Gets the current_publishing_status of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Current version publishing status.  # noqa: E501

        :return: The current_publishing_status of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._current_publishing_status

    @current_publishing_status.setter
    def current_publishing_status(self, current_publishing_status):
        """Sets the current_publishing_status of this V11VmOpenApiElectronicChannelInBase.

        Current version publishing status.  # noqa: E501

        :param current_publishing_status: The current_publishing_status of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._current_publishing_status = current_publishing_status

    @property
    def service_channel_services(self):
        """Gets the service_channel_services of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Internal property for adding service relations for a service channel.  # noqa: E501

        :return: The service_channel_services of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[str]
        """
        return self._service_channel_services

    @service_channel_services.setter
    def service_channel_services(self, service_channel_services):
        """Sets the service_channel_services of this V11VmOpenApiElectronicChannelInBase.

        Internal property for adding service relations for a service channel.  # noqa: E501

        :param service_channel_services: The service_channel_services of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[str]
        """

        self._service_channel_services = service_channel_services

    @property
    def user_name(self):
        """Gets the user_name of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        User name.  # noqa: E501

        :return: The user_name of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this V11VmOpenApiElectronicChannelInBase.

        User name.  # noqa: E501

        :param user_name: The user_name of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    @property
    def service_channel_names(self):
        """Gets the service_channel_names of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Localized list of service channel names. (Max.Length: 100).  # noqa: E501

        :return: The service_channel_names of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiLanguageItem]
        """
        return self._service_channel_names

    @service_channel_names.setter
    def service_channel_names(self, service_channel_names):
        """Sets the service_channel_names of this V11VmOpenApiElectronicChannelInBase.

        Localized list of service channel names. (Max.Length: 100).  # noqa: E501

        :param service_channel_names: The service_channel_names of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiLanguageItem]
        """

        self._service_channel_names = service_channel_names

    @property
    def signature_quantity(self):
        """Gets the signature_quantity of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        How many signatures are required (number). Required if RequiresSignature is true.  # noqa: E501

        :return: The signature_quantity of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._signature_quantity

    @signature_quantity.setter
    def signature_quantity(self, signature_quantity):
        """Sets the signature_quantity of this V11VmOpenApiElectronicChannelInBase.

        How many signatures are required (number). Required if RequiresSignature is true.  # noqa: E501

        :param signature_quantity: The signature_quantity of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._signature_quantity = signature_quantity

    @property
    def requires_signature(self):
        """Gets the requires_signature of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Signature required.  # noqa: E501

        :return: The requires_signature of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._requires_signature

    @requires_signature.setter
    def requires_signature(self, requires_signature):
        """Sets the requires_signature of this V11VmOpenApiElectronicChannelInBase.

        Signature required.  # noqa: E501

        :param requires_signature: The requires_signature of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """

        self._requires_signature = requires_signature

    @property
    def requires_authentication(self):
        """Gets the requires_authentication of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Does the service require authentication.  # noqa: E501

        :return: The requires_authentication of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._requires_authentication

    @requires_authentication.setter
    def requires_authentication(self, requires_authentication):
        """Sets the requires_authentication of this V11VmOpenApiElectronicChannelInBase.

        Does the service require authentication.  # noqa: E501

        :param requires_authentication: The requires_authentication of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """
        if requires_authentication is None:
            raise ValueError("Invalid value for `requires_authentication`, must not be `None`")  # noqa: E501

        self._requires_authentication = requires_authentication

    @property
    def web_page(self):
        """Gets the web_page of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of localized urls. (Max.Length: 500).  # noqa: E501

        :return: The web_page of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiLanguageItem]
        """
        return self._web_page

    @web_page.setter
    def web_page(self, web_page):
        """Sets the web_page of this V11VmOpenApiElectronicChannelInBase.

        List of localized urls. (Max.Length: 500).  # noqa: E501

        :param web_page: The web_page of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiLanguageItem]
        """

        self._web_page = web_page

    @property
    def attachments(self):
        """Gets the attachments of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of attachments.  # noqa: E501

        :return: The attachments of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiAttachment]
        """
        return self._attachments

    @attachments.setter
    def attachments(self, attachments):
        """Sets the attachments of this V11VmOpenApiElectronicChannelInBase.

        List of attachments.  # noqa: E501

        :param attachments: The attachments of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiAttachment]
        """

        self._attachments = attachments

    @property
    def accessibility_classification(self):
        """Gets the accessibility_classification of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        The accessibility classification.  # noqa: E501

        :return: The accessibility_classification of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiAccessibilityClassification]
        """
        return self._accessibility_classification

    @accessibility_classification.setter
    def accessibility_classification(self, accessibility_classification):
        """Sets the accessibility_classification of this V11VmOpenApiElectronicChannelInBase.

        The accessibility classification.  # noqa: E501

        :param accessibility_classification: The accessibility_classification of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiAccessibilityClassification]
        """

        self._accessibility_classification = accessibility_classification

    @property
    def delete_all_attachments(self):
        """Gets the delete_all_attachments of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Set to true to delete all existing attachments. The attachments collection should be empty when this property is set to true.  # noqa: E501

        :return: The delete_all_attachments of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._delete_all_attachments

    @delete_all_attachments.setter
    def delete_all_attachments(self, delete_all_attachments):
        """Sets the delete_all_attachments of this V11VmOpenApiElectronicChannelInBase.

        Set to true to delete all existing attachments. The attachments collection should be empty when this property is set to true.  # noqa: E501

        :param delete_all_attachments: The delete_all_attachments of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """

        self._delete_all_attachments = delete_all_attachments

    @property
    def web_pages(self):
        """Gets the web_pages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of service channel web pages.  # noqa: E501

        :return: The web_pages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[V9VmOpenApiWebPage]
        """
        return self._web_pages

    @web_pages.setter
    def web_pages(self, web_pages):
        """Sets the web_pages of this V11VmOpenApiElectronicChannelInBase.

        List of service channel web pages.  # noqa: E501

        :param web_pages: The web_pages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[V9VmOpenApiWebPage]
        """

        self._web_pages = web_pages

    @property
    def delete_all_web_pages(self):
        """Gets the delete_all_web_pages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Set to true to delete all existing web pages for the service channel. The WebPages collection should be empty when this property is set to true.  # noqa: E501

        :return: The delete_all_web_pages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: bool
        """
        return self._delete_all_web_pages

    @delete_all_web_pages.setter
    def delete_all_web_pages(self, delete_all_web_pages):
        """Sets the delete_all_web_pages of this V11VmOpenApiElectronicChannelInBase.

        Set to true to delete all existing web pages for the service channel. The WebPages collection should be empty when this property is set to true.  # noqa: E501

        :param delete_all_web_pages: The delete_all_web_pages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: bool
        """

        self._delete_all_web_pages = delete_all_web_pages

    @property
    def available_languages(self):
        """Gets the available_languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Gets or sets available languages  # noqa: E501

        :return: The available_languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[str]
        """
        return self._available_languages

    @available_languages.setter
    def available_languages(self, available_languages):
        """Sets the available_languages of this V11VmOpenApiElectronicChannelInBase.

        Gets or sets available languages  # noqa: E501

        :param available_languages: The available_languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[str]
        """

        self._available_languages = available_languages

    @property
    def required_properties_available_languages(self):
        """Gets the required_properties_available_languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Internal property to check the languages within required lists: ServiceChannelNames, ServiceChannelDescriptions,  WebPage and AccessibilityClassification lists.  # noqa: E501

        :return: The required_properties_available_languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[str]
        """
        return self._required_properties_available_languages

    @required_properties_available_languages.setter
    def required_properties_available_languages(self, required_properties_available_languages):
        """Sets the required_properties_available_languages of this V11VmOpenApiElectronicChannelInBase.

        Internal property to check the languages within required lists: ServiceChannelNames, ServiceChannelDescriptions,  WebPage and AccessibilityClassification lists.  # noqa: E501

        :param required_properties_available_languages: The required_properties_available_languages of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[str]
        """

        self._required_properties_available_languages = required_properties_available_languages

    @property
    def service_channel_descriptions(self):
        """Gets the service_channel_descriptions of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of localized service channel descriptions. Possible type values are: Description, Summary. (Max.Length: 150 Summary).  # noqa: E501

        :return: The service_channel_descriptions of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiLocalizedListItem]
        """
        return self._service_channel_descriptions

    @service_channel_descriptions.setter
    def service_channel_descriptions(self, service_channel_descriptions):
        """Sets the service_channel_descriptions of this V11VmOpenApiElectronicChannelInBase.

        List of localized service channel descriptions. Possible type values are: Description, Summary. (Max.Length: 150 Summary).  # noqa: E501

        :param service_channel_descriptions: The service_channel_descriptions of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiLocalizedListItem]
        """

        self._service_channel_descriptions = service_channel_descriptions

    @property
    def area_type(self):
        """Gets the area_type of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Area type. Possible values are: Nationwide, NationwideExceptAlandIslands or LimitedType.  # noqa: E501

        :return: The area_type of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._area_type

    @area_type.setter
    def area_type(self, area_type):
        """Sets the area_type of this V11VmOpenApiElectronicChannelInBase.

        Area type. Possible values are: Nationwide, NationwideExceptAlandIslands or LimitedType.  # noqa: E501

        :param area_type: The area_type of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._area_type = area_type

    @property
    def areas(self):
        """Gets the areas of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of areas. List can contain different types of areas.  # noqa: E501

        :return: The areas of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[VmOpenApiAreaIn]
        """
        return self._areas

    @areas.setter
    def areas(self, areas):
        """Sets the areas of this V11VmOpenApiElectronicChannelInBase.

        List of areas. List can contain different types of areas.  # noqa: E501

        :param areas: The areas of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[VmOpenApiAreaIn]
        """

        self._areas = areas

    @property
    def support_phones(self):
        """Gets the support_phones of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of support phone numbers for the service channel.  # noqa: E501

        :return: The support_phones of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[V4VmOpenApiPhone]
        """
        return self._support_phones

    @support_phones.setter
    def support_phones(self, support_phones):
        """Sets the support_phones of this V11VmOpenApiElectronicChannelInBase.

        List of support phone numbers for the service channel.  # noqa: E501

        :param support_phones: The support_phones of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[V4VmOpenApiPhone]
        """

        self._support_phones = support_phones

    @property
    def service_hours(self):
        """Gets the service_hours of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        List of service channel service hours.  # noqa: E501

        :return: The service_hours of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: list[V11VmOpenApiServiceHour]
        """
        return self._service_hours

    @service_hours.setter
    def service_hours(self, service_hours):
        """Sets the service_hours of this V11VmOpenApiElectronicChannelInBase.

        List of service channel service hours.  # noqa: E501

        :param service_hours: The service_hours of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: list[V11VmOpenApiServiceHour]
        """

        self._service_hours = service_hours

    @property
    def publishing_status(self):
        """Gets the publishing_status of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501

        Service channel publishing status. Values: Draft, Published, Deleted or Modified.  # noqa: E501

        :return: The publishing_status of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :rtype: str
        """
        return self._publishing_status

    @publishing_status.setter
    def publishing_status(self, publishing_status):
        """Sets the publishing_status of this V11VmOpenApiElectronicChannelInBase.

        Service channel publishing status. Values: Draft, Published, Deleted or Modified.  # noqa: E501

        :param publishing_status: The publishing_status of this V11VmOpenApiElectronicChannelInBase.  # noqa: E501
        :type: str
        """

        self._publishing_status = publishing_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V11VmOpenApiElectronicChannelInBase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V11VmOpenApiElectronicChannelInBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
