# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VmOpenApiAreaIn(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'area_codes': 'list[str]',
        'owner_reference_id': 'str'
    }

    attribute_map = {
        'type': 'type',
        'area_codes': 'areaCodes',
        'owner_reference_id': 'ownerReferenceId'
    }

    def __init__(self, type=None, area_codes=None, owner_reference_id=None):  # noqa: E501
        """VmOpenApiAreaIn - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._area_codes = None
        self._owner_reference_id = None
        self.discriminator = None
        self.type = type
        self.area_codes = area_codes
        if owner_reference_id is not None:
            self.owner_reference_id = owner_reference_id

    @property
    def type(self):
        """Gets the type of this VmOpenApiAreaIn.  # noqa: E501

        Type of the area. Possible values are: Municipality, Region, BusinessSubRegion or HospitalDistrict.  In version 7 and older: Municipality, Province, BusinessRegions, HospitalRegions.  # noqa: E501

        :return: The type of this VmOpenApiAreaIn.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this VmOpenApiAreaIn.

        Type of the area. Possible values are: Municipality, Region, BusinessSubRegion or HospitalDistrict.  In version 7 and older: Municipality, Province, BusinessRegions, HospitalRegions.  # noqa: E501

        :param type: The type of this VmOpenApiAreaIn.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def area_codes(self):
        """Gets the area_codes of this VmOpenApiAreaIn.  # noqa: E501

        List of area codes related to type. For example if type = Municipality, areaCodes-list need to include municipality codes like 491 or 091.  # noqa: E501

        :return: The area_codes of this VmOpenApiAreaIn.  # noqa: E501
        :rtype: list[str]
        """
        return self._area_codes

    @area_codes.setter
    def area_codes(self, area_codes):
        """Sets the area_codes of this VmOpenApiAreaIn.

        List of area codes related to type. For example if type = Municipality, areaCodes-list need to include municipality codes like 491 or 091.  # noqa: E501

        :param area_codes: The area_codes of this VmOpenApiAreaIn.  # noqa: E501
        :type: list[str]
        """
        if area_codes is None:
            raise ValueError("Invalid value for `area_codes`, must not be `None`")  # noqa: E501

        self._area_codes = area_codes

    @property
    def owner_reference_id(self):
        """Gets the owner_reference_id of this VmOpenApiAreaIn.  # noqa: E501

        Gets or sets the owner reference identifier.  # noqa: E501

        :return: The owner_reference_id of this VmOpenApiAreaIn.  # noqa: E501
        :rtype: str
        """
        return self._owner_reference_id

    @owner_reference_id.setter
    def owner_reference_id(self, owner_reference_id):
        """Sets the owner_reference_id of this VmOpenApiAreaIn.

        Gets or sets the owner reference identifier.  # noqa: E501

        :param owner_reference_id: The owner_reference_id of this VmOpenApiAreaIn.  # noqa: E501
        :type: str
        """

        self._owner_reference_id = owner_reference_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VmOpenApiAreaIn, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VmOpenApiAreaIn):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
