# coding: utf-8

"""
    PTV Open Api version 11

    Here you can see listed all the PTV Open Api methods.  # noqa: E501

    OpenAPI spec version: v11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VmOpenApiDialCodeListItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'names': 'list[VmOpenApiLanguageItem]',
        'prefix_numbers': 'list[str]'
    }

    attribute_map = {
        'code': 'code',
        'names': 'names',
        'prefix_numbers': 'prefixNumbers'
    }

    def __init__(self, code=None, names=None, prefix_numbers=None):  # noqa: E501
        """VmOpenApiDialCodeListItem - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._names = None
        self._prefix_numbers = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if names is not None:
            self.names = names
        if prefix_numbers is not None:
            self.prefix_numbers = prefix_numbers

    @property
    def code(self):
        """Gets the code of this VmOpenApiDialCodeListItem.  # noqa: E501

        Localized value corresponding to the Language property value.  # noqa: E501

        :return: The code of this VmOpenApiDialCodeListItem.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this VmOpenApiDialCodeListItem.

        Localized value corresponding to the Language property value.  # noqa: E501

        :param code: The code of this VmOpenApiDialCodeListItem.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def names(self):
        """Gets the names of this VmOpenApiDialCodeListItem.  # noqa: E501

        Localized list of names.  # noqa: E501

        :return: The names of this VmOpenApiDialCodeListItem.  # noqa: E501
        :rtype: list[VmOpenApiLanguageItem]
        """
        return self._names

    @names.setter
    def names(self, names):
        """Sets the names of this VmOpenApiDialCodeListItem.

        Localized list of names.  # noqa: E501

        :param names: The names of this VmOpenApiDialCodeListItem.  # noqa: E501
        :type: list[VmOpenApiLanguageItem]
        """

        self._names = names

    @property
    def prefix_numbers(self):
        """Gets the prefix_numbers of this VmOpenApiDialCodeListItem.  # noqa: E501

        List of prefix numbers  # noqa: E501

        :return: The prefix_numbers of this VmOpenApiDialCodeListItem.  # noqa: E501
        :rtype: list[str]
        """
        return self._prefix_numbers

    @prefix_numbers.setter
    def prefix_numbers(self, prefix_numbers):
        """Sets the prefix_numbers of this VmOpenApiDialCodeListItem.

        List of prefix numbers  # noqa: E501

        :param prefix_numbers: The prefix_numbers of this VmOpenApiDialCodeListItem.  # noqa: E501
        :type: list[str]
        """

        self._prefix_numbers = prefix_numbers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VmOpenApiDialCodeListItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VmOpenApiDialCodeListItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
